db:
  image: sameersbn/postgresql:9.4-8
  links:
    - registrator
  environment:
    DB_NAME: faros
    DB_USER: root
    DB_PASS: abc
  ports:
    - 5432:5432

app:
  image: felipesere/faros:latest
  links:
    - db:db
    - registrator
  environment:
    SERVICE_4001_NAME: faros
    SERVICE_NAME: faros
    DB_USER_NAME: root
    DB_USER_PASSWORD: abc
    DATABASE_NAME: faros
    DATABASE_HOST: db
    GITHUB_CLIENT_SECRET: "fee4297faadcf39a8e4e5121aea344e4c40e1e25"
    GITHUB_CLIENT_ID: "0f2543c695f35c9a73bf"
  ports:
    - 4001

consul:
  image: gliderlabs/consul-server
  command: -bootstrap
  hostname: consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  image: gliderlabs/registrator:latest
  command: -ip 172.17.0.1 consul://consul:8500
  hostname: registrator
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

lb:
  image: felipesere/nginx-lb:latest
  links:
    - db
    - app
    - consul
  ports:
    - 80:80
