db:
  image: mysql:latest
  links:
    - registrator
  environment:
    MYSQL_DATABASE: faros
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: abc
  ports:
    - 3306:3306

app:
  image: felipesere/faros:latest
  links:
    - db:db
    - registrator
  environment:
    SERVICE_4001_NAME: faros
    SERVICE_NAME: faros
    DB_USER_NAME: root
    DB_USER_PASSWORD: abc
    DATABASE_NAME: faros
    DATABASE_HOST: db
  ports:
    - 4001

consul:
  image: gliderlabs/consul-server
  command: -bootstrap
  hostname: consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

registrator:
  image: gliderlabs/registrator:latest
  command: -ip 172.17.42.1 consul://consul:8500
  hostname: registrator
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

lb:
  image: felipesere/nginx-lb:latest
  links:
    - db
    - app
    - consul
  ports:
    - 80:80
