use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :faros, Faros.Endpoint,
  http: [port: 4001],
  url: [host: "example.com"],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section:
#
#  config :faros, Faros.Endpoint,
#    ...
#    https: [port: 443,
#            keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#            certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables point to a file on
# disk for the key and cert.

# Do not print debug messages in production
config :logger, level: :info

config :faros, :find_by_isbn, Faros.Books.IsbnLookup

config :faros, Faros.Repo,
  adapter: Ecto.Adapters.MySQL,
    username: "${DB_USER_NAME}",
    password: "${DB_USER_PASSWORD}",
    database: "${DATABASE_NAME}",
    pool: Ecto.Adapters.SQL.Sandbox,
    hostname: "${DATABASE_HOST}",
    size: 10 # The amount of database connections in the pool

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :faros, Faros.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
#import_config "prod.secret.exs"
